// src/components/LoginForm.vue
<script setup lang="ts">
import { ref } from 'vue'

const username = ref('')
const password = ref('')
const error = ref('')

const emit = defineEmits<{
  submit: [username: string, password: string]
}>()

function handleSubmit() {
  if (!username.value) {
    error.value = 'Username is required'
  } else if (!password.value) {
    error.value = 'Password is required'
  } else {
    error.value = ''
    emit('submit', username.value, password.value)
  }
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <h1>Login</h1>
    <div>
      <label for="username">Username:</label>
      <input id="username" v-model="username" type="text" />
    </div>
    <div>
      <label for="password">Password:</label>
      <input id="password" v-model="password" type="password" />
    </div>
    <button type="submit">Submit</button>
    <div v-if="error" role="alert">{{ error }}</div>
  </form>
</template>

// react/src/components/login-form.tsx
import * as React from "react";

type Props = {
  onSubmit: (credentials: { username: string; password: string }) => void;
}
export function Login({ onSubmit } : Props) {
  const [error, setError] = React.useState("");

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const {
      usernameInput: { value: username },
      passwordInput: { value: password },
    } = (event.target as HTMLFormElement).elements;

    if (!username) {
      setError("username is required");
    } else if (!password) {
      setError("password is required");
    } else {
      setError("");
      onSubmit({ username, password });
    }
  }

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <div>
          <label htmlFor="usernameInput">Username</label>
          <input id="usernameInput" />
        </div>
        <div>
          <label htmlFor="passwordInput">Password</label>
          <input id="passwordInput" type="password" />
        </div>
        <button type="submit">Submit</button>
      </form>
      {error ? <div role="alert">{error}</div> : null}
    </div>
  );
}

export default Login;
